```

#returns the number of statements which have a reference to
#something which is a encyclopedia or a reference work

#used SPARQL endpoint: https://query.wikidata.org

SELECT ?enc (COUNT(?enc) as ?count) WHERE {
  ?s ?o ?p.
  ?p prov:wasDerivedFrom ?refnode.
  ?refnode pr:P248 ?enc.
  {?enc wdt:P31 wd:Q5292.}
  UNION
  {?enc wdt:P136 wd:Q13136.}
}
GROUP BY ?enc

```
